---
# CloudBoz - Kernel optimization
- name: "config kernel at /etc/sysctl.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/sysctl.conf
  with_items:
    - cb-sysctl.conf
  tags:
    - install-optimization

- name: "reload kernel at /etc/sysctl.conf"
  shell: sysctl -p
  args:
    executable: /bin/bash
  tags:
    - install-optimization

- name: "config ulimit at /etc/security/limits.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/security/limits.conf
  with_items:
    - cb-limits.conf
  tags:
    - install-optimization

# CloudBoz - Swap memory
# - name: "create swap at /swapfile"
#   command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }} creates="{{ swap_file_path }}"
#   tags:
#     - install-optimization

# - name: "change permissions at /swapfile"
#   file: path="{{ swap_file_path }}"
#         owner=root
#         group=root
#         mode=0600
#   tags:
#     - install-optimization

# - name: "checking type at /swapfile"
#   command: file {{ swap_file_path }}
#   register: swapfile
#   tags:
#     - install-optimization

# - name: "make swap at /swapfile"
#   command: "sudo mkswap {{ swap_file_path }}"
#   when: swapfile.stdout.find('swap file') == -1
#   tags:
#     - install-optimization

# - name: "write swap entry in fstab"
#   mount: name=none
#          src={{ swap_file_path }}
#          fstype=swap
#          opts=sw
#          passno=0
#          dump=0
#          state=present
#   tags:
#     - install-optimization

# - name: "mount /swapfile"
#   command: "swapon {{ swap_file_path }}"
#   when: ansible_swaptotal_mb < 1
#   tags:
#     - install-optimization