# CloudBoz - MariaDB Install
- name: "install mariadb"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ mariadb_docker_name }}"
    image: "{{ mariadb_docker_image }}:{{ mariadb_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ mariadb_docker_name }}-data:/var/lib/mariadb"
    restart_policy: always
    ports:
      - "{{ mariadb_docker_ports }}:3306"
    env:
      MARIADB_ROOT_PASSWORD: "{{ mariadb_docker_env_root_password }}"
      MARIADB_DATABASE: "{{ mariadb_docker_env_database }}"
      MARIADB_USER: "{{ mariadb_docker_env_user }}"
      MARIADB_PASSWORD: "{{ mariadb_docker_env_password }}"
  tags:
    - install-mariadb

# CloudBoz - MariaDB Firewall Install
- name: "'{{ ufw_rule }}' port '{{ mariadb_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ mariadb_docker_ports | quote }}"
  tags:
    - install-mariadb

# CloudBoz - MariaDB Uninstall
- name: "uninstall mariadb"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ mariadb_docker_name }}"
    state: absent
  tags:
    - uninstall-mariadb

# CloudBoz - MariaDB Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ mariadb_docker_ports }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ mariadb_docker_ports | quote }}"
  tags:
    - uninstall-mariadb

# CloudBoz - MariaDB Uninstall with Data
- name: "uninstall mariadb data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ mariadb_docker_name }}-data"
  tags:
    - uninstall-mariadb-data