# ANSIBLE ENV
ansible_connection: ssh
ansible_user: 
ansible_ssh_pass: 
ansible_sudo_pass: 
ansible_ssh_private_key_file: files/secrets/ssh.key
ansible_python_interpreter: /usr/bin/python3

# SSH ENV
pass_auth: PasswordAuthentication yes
pubkey_auth: PubkeyAuthentication yes

# SWAP ENV
swap_file_path: /swapfile
swap_file_size: 2048
swappiness: 1

# DOCKER ENV
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# CADDY ENV
# caddy_apt_repository: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
# caddy_apt_gpg_key: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
# caddy_apt_ignore_key_error: true

# FIREWALL ENV
ufw_rule: allow

# DOMAIN ENV
cloudboz_domain: servermanajer.com
cloudboz_sub_domain: wordpress.user6.servermanajer.com
cloudboz_sub_domain_ip: 13.229.235.168